#!/bin/bash

amount=20
playlistFile=~/.config/mpd/playlists/MostRecent.m3u
pushd ~/Music >> /dev/null
files=`fd --type file --exec stat --printf '%Y\t%n\n' | sort -n --reverse | cut -f2 | head -n $amount`
# files=`find . -printf "%T+\t%p\n" | sort | cut -d$'\t' -f2 | rg "\.(mp3|flac)$" | cut -d'/' -f1 --complement | tail -n$amount` 
echo "${files}" > $playlistFile
echo "updated most recent songs."
cat $playlistFile
popd >> /dev/null
