#!/bin/bash

output=""
for d in ~/Documents/work/*/; do
  cd $d
  status=$(git status 2>/dev/null)
  if [[ $? -eq 0 ]]; then
    status=$(echo -e "$status" | head -n2 | tail -n1)
    # echo "$d: $status"
    output="$output\n$d: $status"
  fi
  cd ..
done

printf "$output" | grep -E "behind|ahead"
